### ISSUE TITLE
buildFederatedSchema ignores custom directives

### ISSUE THREAD

**Issue by padenj** [ExpediaGroup/graphql-component#39]
Apollo's buildFederatedSchema only adds built-in directives to the schema.  It does not honor the schemaDirectives option.  Therefore, any custom directives are ignored.  See issue https://github.com/apollographql/apollo-feature-requests/issues/145.

A workaround could be to use mergeSchemas to add in the schema definition after building the federated schema.

**Comment by tlivings** [comment]
Fixed in #40

**Comment by padenj** [comment]
The fix for this issue causes extended properties to be ignored when publishing a schema to Apollo GraphManager.   PR #41  is a less intrusive way to add custom directives with less side effects on the federated schema.
