### ISSUE TITLE
Bug: resolver wrapping breaks trivial resolvers when type is different than expected in the schema

### ISSUE THREAD

**Issue by jospablos** [ExpediaGroup/graphql-component#87]
Hello team, found an issue with [trivial resolvers](https://graphql.org/learn/execution/#trivial-resolvers) and the resolver wrapping to prevent double executions in delegateToComponent situations. I don't fully understand this double execution issue that relevant code tries to prevent to propose a solution, so I thought I'd create an issue first to discuss.

## Current behavior

The resolution for a graph breaks when on a root object a field is present but with a different type than expected in the schema. Example:

given a type that has a field `name` of type `String`, a root object:
```
{
    ...
    name: {
        value: "name"
    }
    ...
}
```
and field resolver:
```
name(obj) {
    return obj.value
}
```

[These lines](https://github.com/ExpediaGroup/graphql-component/blob/master/lib/resolvers/index.js#L166-L168) will find that there's already the field `name` present in the root and return that, breaking the resolution because we'd be returning an object for a String type.

## Expected behavior

Instead, we'd want the resolution of the type to be [passed through to the trivial resolver](https://github.com/ExpediaGroup/graphql-component/blob/master/lib/resolvers/index.js#L169) and the resolution to not break.

## Maybe solutions

A naive first approach to a solution would be to do a type check (this field expects a string... is the field already a string? return, else pass through to resolver) but the issue remains: even if the expected type matches the type we find, there could be some transformation applied in a trivial resolver (upper case a string, + 1 a zero-based index, I don't know). So maybe there's a better way for a component to know that it is in a delegateToComponent context or to provide an option to explicitly request a resolver NOT to be executed? (maybe an option to pass a list of "noDoubleExecuteResolvers" to compare against)? thoughts?

**Comment by brianjquinn** [comment]
this is ultimately addressed by the release of graphql-component v3 - resolver wrapping has been removed
